### ISSUE TITLE
AsyncServer error

### ISSUE THREAD

**Issue by Alvinhx** [benwtrent/janus-gateway-android#15]
Hi, I just downloaded the code the code and tried to run it on Android 6.0.1.  it crashed at app starting.

FATAL EXCEPTION: AsyncServer
                                                                         Process: computician.janusclient, PID: 18065
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'void com.koushikdutta.async.http.WebSocket.setWriteableCallback(com.koushikdutta.async.callback.WritableCallback)' on a null object reference
                                                                             at computician.janusclientapi.JanusWebsocketMessenger$1.onCompleted(JanusWebsocketMessenger.java:48)
                                                                             at com.koushikdutta.async.http.AsyncHttpClient$11.onConnectCompleted(AsyncHttpClient.java:685)
                                                                             at com.koushikdutta.async.http.AsyncHttpClient.reportConnectedCompleted(AsyncHttpClient.java:169)
                                                                             at com.koushikdutta.async.http.AsyncHttpClient.access$200(AsyncHttpClient.java:50)
                                                                             at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:280)
                                                                             at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:812)
                                                                             at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
                                                                             at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                                                                             at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

I don't quite understand why is it. Can you check on it? thanks!!

**Comment by benwtrent** [comment]
So, it looks like it tried to write to a null object? Looks like you are using the websocket endpoint right? 

Does it work on an earlier release? Before the code changes pushed by @georgekankava?

**Comment by Alvinhx** [comment]
Yes. I'm using websocket endpoint. And I didn't know if it works before,
this is my first time using it. I'm checking my server now..maybe if's my
server's problem.

**Comment by pookie13** [comment]
@Alvinhx, We are also facing the same problem. Was that problem from the server side or due to slow internet connection speed. Please let us know the solution.

Right now we are checking client is null or not before making it writable. if I found that client is null then I am resending `connect()` function again until it connects. As it is not the proper solution because sometimes it takes too many attempts to get register your help will be very helpful to us.

**Comment by MrsZ** [comment]
hi,We are also facing the same problem. Have you solved this problem?How should I deal with this problem? Thanks。

**Comment by Computician** [comment]
https://github.com/koush/AndroidAsync/issues/510 seems related, at least that is the case for those on 4.0.X. Unsure about 6+

**Comment by benwtrent** [comment]
@MrsZ have you tried using the HTTP Client? Or does this happen there as well?

**Comment by benwtrent** [comment]
https://github.com/Computician/janus-gateway-android/blob/master/janusclientapi/src/main/java/computician/janusclientapi/JanusWebsocketMessenger.java#L45

That line, it seems that if an exception has occurred, we should not continue this code path and fail. It may be that there is an exception being returned by the Async client that we are not seeing.

**Comment by MrsZ** [comment]
Yes, do you know how to solve this problem now? My android technology is relatively poor, very hope you can solve this problem. Thanks for your Hard work。

**Comment by benwtrent** [comment]
I am not sure, you could easily check if that exception is null or not and log it to see if we get some more information. 

`Log.d("JANUSCLIENT", ex.toString());` or `Log.d("JANUSCLIENT", Log.getStackTraceString(ex));`. I would also `return` after seeing that the exception is NOT null. 

May also have to step through it with a debugger.

**Comment by sajidjutt7** [comment]
@MrsZ , @pookie13 , @Alvinhx and @benwtrent we are getting same issue in configuring the project using your server address and port.
But as @benwtrent said above to use HTTP client. 
I use my own http server address with port 8080. It ran fine
