### ISSUE TITLE
FATAL EXCEPTION: AsyncServer

### ISSUE THREAD

**Issue by MrsZ** [benwtrent/janus-gateway-android#24]
FATAL EXCEPTION: AsyncServer
                                                   Process: computician.janusclient, PID: 12108
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'void com.koushikdutta.async.http.WebSocket.setWriteableCallback(com.koushikdutta.async.callback.WritableCallback)' on a null object reference
                                                       at computician.janusclientapi.JanusWebsocketMessenger$1.onCompleted(JanusWebsocketMessenger.java:48)
                                                       at com.koushikdutta.async.http.AsyncHttpClient$11.onConnectCompleted(AsyncHttpClient.java:672)
                                                       at com.koushikdutta.async.http.AsyncHttpClient.reportConnectedCompleted(AsyncHttpClient.java:170)
                                                       at com.koushikdutta.async.http.AsyncHttpClient.access$200(AsyncHttpClient.java:51)
                                                       at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:279)
                                                       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:843)
                                                       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
                                                       at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                       at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)

How should I deal with this problem?

**Comment by Computician** [comment]
Is this related to? https://github.com/Computician/janus-gateway-android/issues/22 ? Does that code change help here as well?
